version: '2'
services:
  graphite:
    build: graphite
    restart: always
    container_name: gamergraf-graphite
    ports:
        - "18000:18000"
        - "12003:12003"
        - "12004:12004"
    volumes:
        - "./graphite/data:/opt/graphite/storage/whisper"
    environment:
        - HOST_IP=1.1.1.1
        - HOST=computername
        - HOST_PORT=82
        - AFTERBURNER_PASSWORD=17cc95b4017d496f82

  grafana:
    build: grafana
    restart: always
    container_name: gamergraf-grafana
    ports:
        - "3000:3000"
    volumes:
        - "./grafana/data:/var/lib/grafana"
    links:
        - graphite
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=password
